
[package]
name = "glyphpress-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "sfnt_fuzzer"
path = "fuzz_targets/sfnt_fuzzer.rs"
doc = false

[[bin]]
name = "cmap_fuzzer"
path = "fuzz_targets/cmap_fuzzer.rs"
doc = false

[[bin]]
name = "glyf_fuzzer"
path = "fuzz_targets/glyf_fuzzer.rs"
doc = false

[[bin]]
name = "name_fuzzer"
path = "fuzz_targets/name_fuzzer.rs"
doc = false

[[bin]]
name = "subset_fuzzer"
path = "fuzz_targets/subset_fuzzer.rs"
doc = false

[[bin]]
name = "pipeline_fuzzer"
path = "fuzz_targets/pipeline_fuzzer.rs"
doc = false

[dependencies]
libfuzzer-sys = "0.4"
glyphpress-core = { path = "../glyphpress-core" }
